server:
    port: 9192

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
  application:
    name: PRODUCT-SERVICE
  h2:
    console:
      enabled: true      
            

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka